# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\doron\Documents\Calendar_proj\Calendar_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 258)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 281, 190))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 20, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 20, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 40, 81, 16))
        self.label_4.setObjectName("label_4")
        self.working_days = QtWidgets.QLabel(self.centralwidget)
        self.working_days.setGeometry(QtCore.QRect(430, 20, 41, 16))
        self.working_days.setText("")
        self.working_days.setObjectName("working_days")
        self.worked_days = QtWidgets.QLabel(self.centralwidget)
        self.worked_days.setGeometry(QtCore.QRect(430, 40, 41, 16))
        self.worked_days.setText("")
        self.worked_days.setObjectName("worked_days")
        self.worked_hours = QtWidgets.QLabel(self.centralwidget)
        self.worked_hours.setGeometry(QtCore.QRect(600, 40, 41, 16))
        self.worked_hours.setText("")
        self.worked_hours.setObjectName("worked_hours")
        self.working_hours = QtWidgets.QLabel(self.centralwidget)
        self.working_hours.setGeometry(QtCore.QRect(600, 20, 41, 16))
        self.working_hours.setText("")
        self.working_hours.setObjectName("working_hours")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 721, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Working days:"))
        self.label_2.setText(_translate("MainWindow", "Worked days:"))
        self.label_3.setText(_translate("MainWindow", "Working hours:"))
        self.label_4.setText(_translate("MainWindow", "Worked hours:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
