# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\doron\Documents\ADC_Rabbit_simulator\ADC ticket simulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Choose_SR = QtWidgets.QPushButton(self.centralwidget)
        self.Choose_SR.setGeometry(QtCore.QRect(10, 20, 141, 23))
        self.Choose_SR.setObjectName("Choose_SR")
        self.label_SR = QtWidgets.QLabel(self.centralwidget)
        self.label_SR.setGeometry(QtCore.QRect(10, 50, 371, 16))
        self.label_SR.setObjectName("label_SR")
        self.Choose_ticket = QtWidgets.QPushButton(self.centralwidget)
        self.Choose_ticket.setGeometry(QtCore.QRect(10, 80, 141, 23))
        self.Choose_ticket.setObjectName("Choose_ticket")
        self.label_Ticket = QtWidgets.QLabel(self.centralwidget)
        self.label_Ticket.setGeometry(QtCore.QRect(10, 110, 371, 16))
        self.label_Ticket.setObjectName("label_Ticket")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(120, 150, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_Ticket_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ticket_2.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.label_Ticket_2.setObjectName("label_Ticket_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(210, 20, 256, 301))
        self.listWidget.setObjectName("listWidget")
        self.Choose_ticket_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Choose_ticket_2.setGeometry(QtCore.QRect(10, 260, 131, 31))
        self.Choose_ticket_2.setObjectName("Choose_ticket_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 487, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Choose_SR.setText(_translate("MainWindow", "Choose SR folder"))
        self.label_SR.setText(_translate("MainWindow", " Folder path:"))
        self.Choose_ticket.setText(_translate("MainWindow", "Choose Destination folder"))
        self.label_Ticket.setText(_translate("MainWindow", " Folder path:"))
        self.label_Ticket_2.setText(_translate("MainWindow", "Set iterations"))
        self.Choose_ticket_2.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
